import { NormalizedIcon } from "../../compiler/src/normalize";

export function generateReactComponent(icon: NormalizedIcon): string {
  const componentName = icon.pascalName;

  const defJson = JSON.stringify(
    {
      name: icon.name,
      slug: icon.slug,
      title: icon.title,
      description: icon.description,
      category: icon.category,
      family: icon.family,
      aliases: icon.aliases,
      tags: icon.tags,
      geometry: {
        grid: icon.grid,
        paths: icon.paths,
        filled: icon.filledPaths,
      },
      animation: icon.animation,
      status: icon.status,
    },
    null,
    2
  );

  return `/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: ${icon.sourceFile}
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const ${componentName}Definition: PXIconDefinition = ${defJson};

/**
 * ${componentName} - ${icon.title}
 * ${icon.description}
 * Canonical: ${componentName}
 * Package: @pxui/react
 * Category: ${icon.category}
 * Grid: 24x24
 */
export const ${componentName} = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={${componentName}Definition} {...props} />;
  }
);

${componentName}.displayName = "${componentName}";

export default ${componentName};
`;
}
