/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/subtract-circle.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSubtractCircleDefinition: PXIconDefinition = {
  "name": "PXIconSubtractCircle",
  "slug": "px-subtract-circle",
  "title": "Subtract Circle",
  "description": "Subtraction or decrement action contained within a circular control.",
  "category": "actions-controls",
  "family": "subtract",
  "aliases": [
    "minus-circle",
    "decrease-circle",
    "decrement-circle"
  ],
  "tags": [
    "subtract",
    "minus",
    "circle",
    "decrease",
    "decrement",
    "math",
    "value"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M8 2h8v1h2v1h2v1h1v3h1v8h-1v3h-1v1h-2v1h-2v1H8v-1H6v-1H4v-1H3v-3H2V8h1V5h1V4h2V3h2V2z M9 5h6v1h2v2h1v8h-1v2h-2v1H9v-1H7v-2H6V8h1V6h2V5z M7 11h10v2H7v-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconSubtractCircle - Subtract Circle
 * Subtraction or decrement action contained within a circular control.
 * Canonical: PXIconSubtractCircle
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSubtractCircle = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSubtractCircleDefinition as any} {...props} />;
  }
);

PXIconSubtractCircle.displayName = "PXIconSubtractCircle";

export default PXIconSubtractCircle;
