/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/copy.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCopyDefinition: PXIconDefinition = {
  "name": "PXIconCopy",
  "slug": "px-copy",
  "title": "Copy",
  "description": "Pixel icon for copy; base form.",
  "category": "actions-controls",
  "family": "copy",
  "aliases": [
    "duplicate",
    "clone",
    "replicate",
    "clipboard-copy"
  ],
  "tags": [
    "copy",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M8 4h12v12h-4v-2h2V6h-8v2H8V4z M4 8h12v12H4V8zm2 2v8h8v-8H6z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconCopy - Copy
 * Pixel icon for copy; base form.
 * Canonical: PXIconCopy
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconCopy = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCopyDefinition} {...props} />;
  }
);

PXIconCopy.displayName = "PXIconCopy";

export default PXIconCopy;
