/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/edit-square.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconEditSquareDefinition: PXIconDefinition = {
  "name": "PXIconEditSquare",
  "slug": "px-edit-square",
  "title": "Edit Square",
  "description": "Represents an editing action within a square or modular interface control.",
  "category": "actions-controls",
  "family": "edit",
  "aliases": [
    "modify-square",
    "pencil-square",
    "update-square"
  ],
  "tags": [
    "edit",
    "modify",
    "square",
    "control",
    "pencil",
    "module"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v2h2v14h-2v2H5v-2H3V5h2V3z M7 17h2v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2V7h-2v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v2H7v2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconEditSquare - Edit Square
 * Represents an editing action within a square or modular interface control.
 * Canonical: PXIconEditSquare
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconEditSquare = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconEditSquareDefinition as any} {...props} />;
  }
);

PXIconEditSquare.displayName = "PXIconEditSquare";

export default PXIconEditSquare;
