/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/business/trending-up.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconTrendingUpDefinition: PXIconDefinition = {
  "name": "PXIconTrendingUp",
  "slug": "px-trending-up",
  "title": "Trending Up",
  "description": "Stepped diagonal growth graph rising from bottom left to top right.",
  "category": "business",
  "family": "trending",
  "aliases": [
    "growth",
    "chart",
    "analytics"
  ],
  "tags": [
    "growth",
    "increase",
    "metrics",
    "chart",
    "analytics"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M16 4h5v5h-2V7.4l-6.3 6.3-3.3-3.3L3.7 16 2.3 14.6l7.1-7.1 3.3 3.3L17.6 6H16V4zM3 20h18v2H3v-2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconTrendingUp - Trending Up
 * Stepped diagonal growth graph rising from bottom left to top right.
 * Canonical: PXIconTrendingUp
 * Package: @pxui/react
 * Category: business
 * Grid: 24x24
 */
export const PXIconTrendingUp = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconTrendingUpDefinition as any} {...props} />;
  }
);

PXIconTrendingUp.displayName = "PXIconTrendingUp";

export default PXIconTrendingUp;
