/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/time/clock.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconClockDefinition: PXIconDefinition = {
  "name": "PXIconClock",
  "slug": "px-clock",
  "title": "Clock",
  "description": "Analog watch dial with circular border and hands at 3:00.",
  "category": "time",
  "family": "clock",
  "aliases": [
    "time",
    "history",
    "recent"
  ],
  "tags": [
    "time",
    "hours",
    "schedule",
    "history",
    "recent"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zm0 2a8 8 0 1 1 0 16 8 8 0 0 1 0-16zm-1 3v6h5v-2h-3V7h-2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconClock - Clock
 * Analog watch dial with circular border and hands at 3:00.
 * Canonical: PXIconClock
 * Package: @pxui/react
 * Category: time
 * Grid: 24x24
 */
export const PXIconClock = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconClockDefinition} {...props} />;
  }
);

PXIconClock.displayName = "PXIconClock";

export default PXIconClock;
