/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/devices/laptop.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconLaptopDefinition: PXIconDefinition = {
  "name": "PXIconLaptop",
  "slug": "px-laptop",
  "title": "Laptop",
  "description": "Portable clamshell notebook computer with keyboard base.",
  "category": "devices",
  "family": "laptop",
  "aliases": [
    "notebook",
    "macbook"
  ],
  "tags": [
    "notebook",
    "macbook",
    "computer",
    "portable"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 4h16v11H4V4zm2 2v7h12V6H6zm-4 10h20v4H2v-4zm8 1h4v1h-4v-1z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconLaptop - Laptop
 * Portable clamshell notebook computer with keyboard base.
 * Canonical: PXIconLaptop
 * Package: @pxui/react
 * Category: devices
 * Grid: 24x24
 */
export const PXIconLaptop = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconLaptopDefinition} {...props} />;
  }
);

PXIconLaptop.displayName = "PXIconLaptop";

export default PXIconLaptop;
