/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/security/lock.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconLockDefinition: PXIconDefinition = {
  "name": "PXIconLock",
  "slug": "px-lock",
  "title": "Lock",
  "description": "Secured padlock with closed curved shackle and body keyhole.",
  "category": "security",
  "family": "lock",
  "aliases": [
    "padlock",
    "secure",
    "private"
  ],
  "tags": [
    "padlock",
    "secure",
    "private",
    "encrypted",
    "protection"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M7 8V6a5 5 0 0 1 10 0v2h2v14H5V8h2zm2 0h6V6a3 3 0 0 0-6 0v2zm-2 2v10h10V10H7zm5 3a1.5 1.5 0 0 1 1 1.4v1.6h-2v-1.6c0-.6.4-1.2 1-1.4z"
      }
    ],
    "filled": [
      {
        "d": "M7 8V6a5 5 0 0 1 10 0v2h2v14H5V8h2zm2 0h6V6a3 3 0 0 0-6 0v2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconLock - Lock
 * Secured padlock with closed curved shackle and body keyhole.
 * Canonical: PXIconLock
 * Package: @pxui/react
 * Category: security
 * Grid: 24x24
 */
export const PXIconLock = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconLockDefinition} {...props} />;
  }
);

PXIconLock.displayName = "PXIconLock";

export default PXIconLock;
