/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/sync-active.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSyncActiveDefinition: PXIconDefinition = {
  "name": "PXIconSyncActive",
  "slug": "px-sync-active",
  "title": "Sync Active",
  "description": "Pixel icon for sync; active state.",
  "category": "actions-controls",
  "family": "sync",
  "aliases": [
    "syncing",
    "synchronized"
  ],
  "tags": [
    "sync",
    "active",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 8h2v4H4V8zm2-2h2v2H6V6zm2-2h7v2H8V4zm6-2h2v2h-2V2zm1 2h4v2h-4V4zm-1 2h2v2h-2V6z M18 12h2v4h-2v-4zm-2 4h2v2h-2v-2zm-7 2h7v2H9v-2zm-1 2h2v2H8v-2zm-3-2h4v2H5v-2zm3-2h2v2H8v-2z M10 10h4v4h-4z",
        "fillRule": "evenodd"
      }
    ]
  },
  "animation": {
    "type": "spin",
    "family": "loop",
    "trigger": "always"
  },
  "status": "experimental"
};

/**
 * PXIconSyncActive - Sync Active
 * Pixel icon for sync; active state.
 * Canonical: PXIconSyncActive
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSyncActive = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSyncActiveDefinition} {...props} />;
  }
);

PXIconSyncActive.displayName = "PXIconSyncActive";

export default PXIconSyncActive;
