/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/arrows/arrow-left.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconArrowLeftDefinition: PXIconDefinition = {
  "name": "PXIconArrowLeft",
  "slug": "px-arrow-left",
  "title": "Arrow Left",
  "description": "Stepped pixel arrow pointing toward the left.",
  "category": "arrows",
  "family": "arrow",
  "aliases": [
    "back",
    "left"
  ],
  "tags": [
    "left",
    "back",
    "previous",
    "direction"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M10 5l-7 7 7 7 1.4-1.4L6.8 13H21v-2H6.8l4.6-4.6L10 5z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconArrowLeft - Arrow Left
 * Stepped pixel arrow pointing toward the left.
 * Canonical: PXIconArrowLeft
 * Package: @pxui/react
 * Category: arrows
 * Grid: 24x24
 */
export const PXIconArrowLeft = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconArrowLeftDefinition as any} {...props} />;
  }
);

PXIconArrowLeft.displayName = "PXIconArrowLeft";

export default PXIconArrowLeft;
