/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/media/camera.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCameraDefinition: PXIconDefinition = {
  "name": "PXIconCamera",
  "slug": "px-camera",
  "title": "Camera",
  "description": "Handheld photography camera body with lens ring and flash nub.",
  "category": "media",
  "family": "camera",
  "aliases": [
    "photo",
    "capture"
  ],
  "tags": [
    "photo",
    "picture",
    "lens",
    "capture",
    "snapshot"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 5h4l2-2h4l2 2h4v16H4V5zm2 2v12h12V7H6zm6 3a3 3 0 1 1 0 6 3 3 0 0 1 0-6zm0 2a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"
      }
    ],
    "filled": [
      {
        "d": "M4 5h4l2-2h4l2 2h4v16H4V5zm8 4a3 3 0 1 0 0 6 3 3 0 0 0 0-6z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconCamera - Camera
 * Handheld photography camera body with lens ring and flash nub.
 * Canonical: PXIconCamera
 * Package: @pxui/react
 * Category: media
 * Grid: 24x24
 */
export const PXIconCamera = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCameraDefinition} {...props} />;
  }
);

PXIconCamera.displayName = "PXIconCamera";

export default PXIconCamera;
