/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/refresh-down.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconRefreshDownDefinition: PXIconDefinition = {
  "name": "PXIconRefreshDown",
  "slug": "px-refresh-down",
  "title": "Refresh Down",
  "description": "Pixel icon for refresh; down-oriented variant.",
  "category": "actions-controls",
  "family": "refresh",
  "aliases": [
    "reload-down",
    "refresh-vertical-down"
  ],
  "tags": [
    "refresh",
    "down",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M11 16v2H9v2h2v2h2v-2h2v-2h-2v-2h-2z M9 4h5v2h-5z M7 6h2v2h-2z M5 8h2v5h-2z M7 13h2v2h-2z M9 15h4v2h-4z M13 13h2v2h-2z M15 10h2v3h-2z M16 7h2v2h-2z M15 6h2v2h-2z M16 4h2v2h-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "animation": {
    "type": "spin",
    "family": "loop",
    "trigger": "always"
  },
  "status": "experimental"
};

/**
 * PXIconRefreshDown - Refresh Down
 * Pixel icon for refresh; down-oriented variant.
 * Canonical: PXIconRefreshDown
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconRefreshDown = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconRefreshDownDefinition} {...props} />;
  }
);

PXIconRefreshDown.displayName = "PXIconRefreshDown";

export default PXIconRefreshDown;
