/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/time/timer.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconTimerDefinition: PXIconDefinition = {
  "name": "PXIconTimer",
  "slug": "px-timer",
  "title": "Timer",
  "description": "Precision stopwatch with top activation pusher stem.",
  "category": "time",
  "family": "timer",
  "aliases": [
    "stopwatch",
    "countdown"
  ],
  "tags": [
    "stopwatch",
    "countdown",
    "seconds",
    "duration",
    "interval"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M10 2h4v2h-4V2zm2 4a8 8 0 1 0 8 8 8 8 0 0 0-8-8zm0 2a6 6 0 1 1-6 6 6 6 0 0 1 6-6zm-1 2v5h4v-2h-2v-3h-2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconTimer - Timer
 * Precision stopwatch with top activation pusher stem.
 * Canonical: PXIconTimer
 * Package: @pxui/react
 * Category: time
 * Grid: 24x24
 */
export const PXIconTimer = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconTimerDefinition as any} {...props} />;
  }
);

PXIconTimer.displayName = "PXIconTimer";

export default PXIconTimer;
