/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/media/play.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconPlayDefinition: PXIconDefinition = {
  "name": "PXIconPlay",
  "slug": "px-play",
  "title": "Play",
  "description": "Stepped pixel equilateral triangle pointing right for media playback.",
  "category": "media",
  "family": "play",
  "aliases": [
    "start",
    "resume"
  ],
  "tags": [
    "start",
    "video",
    "audio",
    "resume",
    "stream"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M6 4l14 8-14 8V4zm2 3.5v9l8-4.5-8-4.5z"
      }
    ],
    "filled": [
      {
        "d": "M6 4l14 8-14 8V4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconPlay - Play
 * Stepped pixel equilateral triangle pointing right for media playback.
 * Canonical: PXIconPlay
 * Package: @pxui/react
 * Category: media
 * Grid: 24x24
 */
export const PXIconPlay = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconPlayDefinition as any} {...props} />;
  }
);

PXIconPlay.displayName = "PXIconPlay";

export default PXIconPlay;
