/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/files/folder-open.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconFolderOpenDefinition: PXIconDefinition = {
  "name": "PXIconFolderOpen",
  "slug": "px-folder-open",
  "title": "Folder Open",
  "description": "Directory folder in an open state revealing contents.",
  "category": "files",
  "family": "folder",
  "aliases": [
    "open-folder"
  ],
  "tags": [
    "directory",
    "active",
    "open",
    "browse"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 4h7l2 2h9v4h-2V8H5v10h2v2H3V4zm4 6h15l-3 10H4l3-10zm2 2l-1.8 6h11.6l1.8-6H9z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconFolderOpen - Folder Open
 * Directory folder in an open state revealing contents.
 * Canonical: PXIconFolderOpen
 * Package: @pxui/react
 * Category: files
 * Grid: 24x24
 */
export const PXIconFolderOpen = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconFolderOpenDefinition} {...props} />;
  }
);

PXIconFolderOpen.displayName = "PXIconFolderOpen";

export default PXIconFolderOpen;
