/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/share-small.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconShareSmallDefinition: PXIconDefinition = {
  "name": "PXIconShareSmall",
  "slug": "px-share-small",
  "title": "Share Small",
  "description": "Pixel icon for share; compact variant.",
  "category": "actions-controls",
  "family": "share",
  "aliases": [
    "send-small",
    "share-compact"
  ],
  "tags": [
    "share",
    "small",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M6 10h3v3H6z M15 6h3v3h-3z M15 15h3v3h-3z M9 9h2v2H9z M11 8h2v2h-2z M13 6h2v2h-2z M9 12h2v2H9z M11 13h2v2h-2z M13 15h2v2h-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconShareSmall - Share Small
 * Pixel icon for share; compact variant.
 * Canonical: PXIconShareSmall
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconShareSmall = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconShareSmallDefinition} {...props} />;
  }
);

PXIconShareSmall.displayName = "PXIconShareSmall";

export default PXIconShareSmall;
