/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/devices/hard-drive.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconHardDriveDefinition: PXIconDefinition = {
  "name": "PXIconHardDrive",
  "slug": "px-hard-drive",
  "title": "Hard Drive",
  "description": "Internal disk drive unit with front status activity indicator LEDs.",
  "category": "devices",
  "family": "hard",
  "aliases": [
    "disk",
    "drive"
  ],
  "tags": [
    "disk",
    "storage",
    "ssd",
    "hdd",
    "hardware"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 5h18v14H3V5zm2 2v10h14V7H5zm10 7h2v2h-2v-2zm-3 0h2v2h-2v-2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconHardDrive - Hard Drive
 * Internal disk drive unit with front status activity indicator LEDs.
 * Canonical: PXIconHardDrive
 * Package: @pxui/react
 * Category: devices
 * Grid: 24x24
 */
export const PXIconHardDrive = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconHardDriveDefinition as any} {...props} />;
  }
);

PXIconHardDrive.displayName = "PXIconHardDrive";

export default PXIconHardDrive;
