/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/add-square.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconAddSquareDefinition: PXIconDefinition = {
  "name": "PXIconAddSquare",
  "slug": "px-add-square",
  "title": "Add Square",
  "description": "Add action contained within a square module or bounded interface region.",
  "category": "actions-controls",
  "family": "add",
  "aliases": [
    "plus-square",
    "create-square",
    "new-box"
  ],
  "tags": [
    "action",
    "square",
    "container",
    "create",
    "add"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v2h2v14h-2v2H5v-2H3V5h2V3z M11 7h2v3h4v2h-4v3h-2v-3H7v-2h4V7z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconAddSquare - Add Square
 * Add action contained within a square module or bounded interface region.
 * Canonical: PXIconAddSquare
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconAddSquare = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconAddSquareDefinition} {...props} />;
  }
);

PXIconAddSquare.displayName = "PXIconAddSquare";

export default PXIconAddSquare;
