/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/development/database.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconDatabaseDefinition: PXIconDefinition = {
  "name": "PXIconDatabase",
  "slug": "px-database",
  "title": "Database",
  "description": "Stacked cylindrical storage platters representing database tables and SQL.",
  "category": "development",
  "family": "database",
  "aliases": [
    "sql",
    "storage",
    "db"
  ],
  "tags": [
    "sql",
    "data",
    "storage",
    "server",
    "postgres"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M12 3c4.4 0 8 1.3 8 3v12c0 1.7-3.6 3-8 3s-8-1.3-8-3V6c0-1.7 3.6-3 8-3zm0 2C8.7 5 6 6 6 6s2.7 1 6 1 6-1 6-1-2.7-1-6-1zm6 4.8c-.8.5-2.2.9-4 1.1V13h-4v-2.1c-1.8-.2-3.2-.6-4-1.1V12c0 .4 2.7 1.5 6 1.5s6-1.1 6-1.5V9.8zm0 5c-.8.5-2.2.9-4 1.1V18h-4v-2.1c-1.8-.2-3.2-.6-4-1.1V17c0 .4 2.7 1.5 6 1.5s6-1.1 6-1.5v-2.2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconDatabase - Database
 * Stacked cylindrical storage platters representing database tables and SQL.
 * Canonical: PXIconDatabase
 * Package: @pxui/react
 * Category: development
 * Grid: 24x24
 */
export const PXIconDatabase = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconDatabaseDefinition} {...props} />;
  }
);

PXIconDatabase.displayName = "PXIconDatabase";

export default PXIconDatabase;
