/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/files/folder.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconFolderDefinition: PXIconDefinition = {
  "name": "PXIconFolder",
  "slug": "px-folder",
  "title": "Folder",
  "description": "File directory container with top left tab.",
  "category": "files",
  "family": "folder",
  "aliases": [
    "directory"
  ],
  "tags": [
    "directory",
    "storage",
    "files",
    "documents"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 4h7l2 2h9v14H3V4zm2 4v10h14V8H5zm0-2h4.6l-2-2H5v2z"
      }
    ],
    "filled": [
      {
        "d": "M3 4h7l2 2h9v14H3V4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconFolder - Folder
 * File directory container with top left tab.
 * Canonical: PXIconFolder
 * Package: @pxui/react
 * Category: files
 * Grid: 24x24
 */
export const PXIconFolder = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconFolderDefinition as any} {...props} />;
  }
);

PXIconFolder.displayName = "PXIconFolder";

export default PXIconFolder;
