/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/save-square.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSaveSquareDefinition: PXIconDefinition = {
  "name": "PXIconSaveSquare",
  "slug": "px-save-square",
  "title": "Save Square",
  "description": "Pixel icon for save; square container.",
  "category": "actions-controls",
  "family": "save",
  "aliases": [
    "store-square",
    "persist-square",
    "disk-square"
  ],
  "tags": [
    "save",
    "square",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v2h2v14h-2v2H5v-2H3V5h2V3z M7 7h9v1h1v9H7V7zm2 2h5v2H9V9zm1 4h5v3h-5v-3z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconSaveSquare - Save Square
 * Pixel icon for save; square container.
 * Canonical: PXIconSaveSquare
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSaveSquare = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSaveSquareDefinition} {...props} />;
  }
);

PXIconSaveSquare.displayName = "PXIconSaveSquare";

export default PXIconSaveSquare;
