/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/toggle-left.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconToggleLeftDefinition: PXIconDefinition = {
  "name": "PXIconToggleLeft",
  "slug": "px-toggle-left",
  "title": "Toggle Left",
  "description": "Pill switch toggled to the left off position.",
  "category": "actions",
  "family": "toggle",
  "aliases": [
    "switch-off"
  ],
  "tags": [
    "switch",
    "off",
    "disabled",
    "state"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M7 6h10a6 6 0 0 1 0 12H7A6 6 0 0 1 7 6zm0 2a4 4 0 0 0 0 8h10a4 4 0 0 0 0-8H7zm0 2a2 2 0 1 1 0 4 2 2 0 0 1 0-4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconToggleLeft - Toggle Left
 * Pill switch toggled to the left off position.
 * Canonical: PXIconToggleLeft
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconToggleLeft = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconToggleLeftDefinition} {...props} />;
  }
);

PXIconToggleLeft.displayName = "PXIconToggleLeft";

export default PXIconToggleLeft;
