/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/zoom-out.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconZoomOutDefinition: PXIconDefinition = {
  "name": "PXIconZoomOut",
  "slug": "px-zoom-out",
  "title": "Zoom Out",
  "description": "Magnifier lens containing a stepped minus sign for scaling downward.",
  "category": "actions",
  "family": "zoom",
  "aliases": [
    "magnify-minus",
    "shrink"
  ],
  "tags": [
    "shrink",
    "scale-down",
    "minus",
    "reduce"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M9 3h6v2h2v2h2v6h-2v2h-2v2H9v-2H7v-2H5V9h2V7h2V5zm6 4H9v6h6V7zm1 8h2v2h-2zm2 2h2v2h-2zm2 2h2v2h-2zm-7-6h4v2H9v-2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconZoomOut - Zoom Out
 * Magnifier lens containing a stepped minus sign for scaling downward.
 * Canonical: PXIconZoomOut
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconZoomOut = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconZoomOutDefinition as any} {...props} />;
  }
);

PXIconZoomOut.displayName = "PXIconZoomOut";

export default PXIconZoomOut;
