/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/checkbox-checked.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCheckboxCheckedDefinition: PXIconDefinition = {
  "name": "PXIconCheckboxChecked",
  "slug": "px-checkbox-checked",
  "title": "Checkbox Checked",
  "description": "Represents a checkbox control in its selected state.",
  "category": "actions-controls",
  "family": "checkbox",
  "aliases": [
    "checkbox",
    "checked",
    "selected-checkbox",
    "checkbox-on"
  ],
  "tags": [
    "form",
    "selection",
    "control",
    "boolean",
    "checked"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v1h1v1h1v14h-1v1h-1v1H5v-1H4v-1H3V5h1V4h1V3zm0 2v14h14V5H5z M7 11h2v1h1v1h1v1h1v-1h1v-1h1v-1h1v-1h2v2h-1v1h-1v1h-1v1h-1v1h-1v1h-2v-1h-1v-1h-1v-1H7v-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconCheckboxChecked - Checkbox Checked
 * Represents a checkbox control in its selected state.
 * Canonical: PXIconCheckboxChecked
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconCheckboxChecked = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCheckboxCheckedDefinition as any} {...props} />;
  }
);

PXIconCheckboxChecked.displayName = "PXIconCheckboxChecked";

export default PXIconCheckboxChecked;
