/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/share-active.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconShareActiveDefinition: PXIconDefinition = {
  "name": "PXIconShareActive",
  "slug": "px-share-active",
  "title": "Share Active",
  "description": "Pixel icon for share; active state.",
  "category": "actions-controls",
  "family": "share",
  "aliases": [
    "shared",
    "share-on"
  ],
  "tags": [
    "share",
    "active",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 10h4v4H4z M16 4h4v4h-4z M16 16h4v4h-4z M8 10h2v2H8z M10 8h2v2h-2z M12 6h2v2h-2z M14 4h2v2h-2z M8 12h2v2H8z M10 14h2v2h-2z M12 16h2v2h-2z M14 18h2v2h-2z M10 10h4v4h-4z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconShareActive - Share Active
 * Pixel icon for share; active state.
 * Canonical: PXIconShareActive
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconShareActive = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconShareActiveDefinition} {...props} />;
  }
);

PXIconShareActive.displayName = "PXIconShareActive";

export default PXIconShareActive;
