/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/arrows/chevron-down.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconChevronDownDefinition: PXIconDefinition = {
  "name": "PXIconChevronDown",
  "slug": "px-chevron-down",
  "title": "Chevron Down",
  "description": "Stepped pixel chevron angle bracket pointing down.",
  "category": "arrows",
  "family": "chevron",
  "aliases": [
    "angle-down",
    "dropdown"
  ],
  "tags": [
    "down",
    "angle",
    "expand",
    "dropdown"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 9l1.4-1.4L12 14.2l6.6-6.6L20 9l-8 8-8-8z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconChevronDown - Chevron Down
 * Stepped pixel chevron angle bracket pointing down.
 * Canonical: PXIconChevronDown
 * Package: @pxui/react
 * Category: arrows
 * Grid: 24x24
 */
export const PXIconChevronDown = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconChevronDownDefinition} {...props} />;
  }
);

PXIconChevronDown.displayName = "PXIconChevronDown";

export default PXIconChevronDown;
