/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/media/image.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconImageDefinition: PXIconDefinition = {
  "name": "PXIconImage",
  "slug": "px-image",
  "title": "Image",
  "description": "Framed artwork with stepped mountains and sun disc.",
  "category": "media",
  "family": "image",
  "aliases": [
    "photo",
    "picture",
    "gallery"
  ],
  "tags": [
    "photo",
    "picture",
    "gallery",
    "scenery",
    "wallpaper"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 3h18v18H3V3zm2 2v14h14V5H5zm3 3a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm10 9l-4-5-3 4-2-2-3 3h12z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconImage - Image
 * Framed artwork with stepped mountains and sun disc.
 * Canonical: PXIconImage
 * Package: @pxui/react
 * Category: media
 * Grid: 24x24
 */
export const PXIconImage = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconImageDefinition as any} {...props} />;
  }
);

PXIconImage.displayName = "PXIconImage";

export default PXIconImage;
