/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/security/eye.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconEyeDefinition: PXIconDefinition = {
  "name": "PXIconEye",
  "slug": "px-eye",
  "title": "Eye",
  "description": "Stepped pixel ocular eyelid silhouette with central iris pupil.",
  "category": "security",
  "family": "eye",
  "aliases": [
    "view",
    "visible",
    "show"
  ],
  "tags": [
    "view",
    "visible",
    "show",
    "watch",
    "preview"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M12 4.5C7 4.5 2.7 7.6 1 12c1.7 4.4 6 7.5 11 7.5s9.3-3.1 11-7.5c-1.7-4.4-6-7.5-11-7.5zm0 13c-3.8 0-7.1-2.4-8.7-5.5C4.9 8.9 8.2 6.5 12 6.5s7.1 2.4 8.7 5.5c-1.6 3.1-4.9 5.5-8.7 5.5zm0-8.5a3 3 0 1 0 0 6 3 3 0 0 0 0-6zm0 2a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconEye - Eye
 * Stepped pixel ocular eyelid silhouette with central iris pupil.
 * Canonical: PXIconEye
 * Package: @pxui/react
 * Category: security
 * Grid: 24x24
 */
export const PXIconEye = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconEyeDefinition} {...props} />;
  }
);

PXIconEye.displayName = "PXIconEye";

export default PXIconEye;
