/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/clear-square.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconClearSquareDefinition: PXIconDefinition = {
  "name": "PXIconClearSquare",
  "slug": "px-clear-square",
  "title": "Clear Square",
  "description": "Clears or resets transient content within a square or modular interface context.",
  "category": "actions-controls",
  "family": "clear",
  "aliases": [
    "reset-square",
    "cancel-square"
  ],
  "tags": [
    "clear",
    "square",
    "reset",
    "input",
    "state",
    "module",
    "erase"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v2h2v14h-2v2H5v-2H3V5h2V3z M7 7h2v1h1v1h1v1h1v1h1v1h1v1h1v1h2v2h-2v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1h-1v-1H7V7z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconClearSquare - Clear Square
 * Clears or resets transient content within a square or modular interface context.
 * Canonical: PXIconClearSquare
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconClearSquare = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconClearSquareDefinition as any} {...props} />;
  }
);

PXIconClearSquare.displayName = "PXIconClearSquare";

export default PXIconClearSquare;
