/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/link.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconLinkDefinition: PXIconDefinition = {
  "name": "PXIconLink",
  "slug": "px-link",
  "title": "Link",
  "description": "Interlocked oval chain links signifying hyperlinking and connection.",
  "category": "actions",
  "family": "link",
  "aliases": [
    "url",
    "chain",
    "hyperlink"
  ],
  "tags": [
    "url",
    "hyperlink",
    "chain",
    "connect",
    "attachment"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M10 13a5 5 0 0 0 7.5.5l3-3a5 5 0 0 0-7-7l-1.5 1.5 1.4 1.4 1.5-1.5a3 3 0 0 1 4.2 4.2l-3 3a3 3 0 0 1-4.3-.3L10 13zm4-2a5 5 0 0 0-7.5-.5l-3 3a5 5 0 0 0 7 7l1.5-1.5-1.4-1.4-1.5 1.5a3 3 0 0 1-4.2-4.2l3-3a3 3 0 0 1 4.3.3L14 11z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconLink - Link
 * Interlocked oval chain links signifying hyperlinking and connection.
 * Canonical: PXIconLink
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconLink = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconLinkDefinition as any} {...props} />;
  }
);

PXIconLink.displayName = "PXIconLink";

export default PXIconLink;
