/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/files/archive.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconArchiveDefinition: PXIconDefinition = {
  "name": "PXIconArchive",
  "slug": "px-archive",
  "title": "Archive",
  "description": "Storage chest or archive box with front pull handle.",
  "category": "files",
  "family": "archive",
  "aliases": [
    "backup",
    "box"
  ],
  "tags": [
    "box",
    "backup",
    "vault",
    "history",
    "store"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 3h18v5H3V3zm1 7h16v11H4V10zm2 2v7h12v-7H6zm3 1h6v2H9v-2zM5 5v1h14V5H5z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconArchive - Archive
 * Storage chest or archive box with front pull handle.
 * Canonical: PXIconArchive
 * Package: @pxui/react
 * Category: files
 * Grid: 24x24
 */
export const PXIconArchive = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconArchiveDefinition as any} {...props} />;
  }
);

PXIconArchive.displayName = "PXIconArchive";

export default PXIconArchive;
