/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/filter.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconFilterDefinition: PXIconDefinition = {
  "name": "PXIconFilter",
  "slug": "px-filter",
  "title": "Filter",
  "description": "Funnel shaped device for sorting, narrowing, and query refinement.",
  "category": "actions",
  "family": "filter",
  "aliases": [
    "funnel",
    "refine"
  ],
  "tags": [
    "sort",
    "funnel",
    "refine",
    "criteria",
    "narrow"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 4h18v2l-7 7v7l-4-2v-5L3 6V4zm3.2 2l5.8 5.8V16l2 1v-5.2l5.8-5.8H6.2z"
      }
    ],
    "filled": [
      {
        "d": "M3 4h18v2l-7 7v7l-4-2v-5L3 6V4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconFilter - Filter
 * Funnel shaped device for sorting, narrowing, and query refinement.
 * Canonical: PXIconFilter
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconFilter = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconFilterDefinition} {...props} />;
  }
);

PXIconFilter.displayName = "PXIconFilter";

export default PXIconFilter;
