/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/upload.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconUploadDefinition: PXIconDefinition = {
  "name": "PXIconUpload",
  "slug": "px-upload",
  "title": "Upload",
  "description": "Stepped up arrow out of a tray for uploading data or assets.",
  "category": "actions",
  "family": "upload",
  "aliases": [
    "send",
    "push"
  ],
  "tags": [
    "send",
    "push",
    "transfer",
    "arrow-up"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M12 3l4 5h-3v8h-2V8H8l4-5zM4 17h2v3h12v-3h2v5H4v-5z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconUpload - Upload
 * Stepped up arrow out of a tray for uploading data or assets.
 * Canonical: PXIconUpload
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconUpload = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconUploadDefinition as any} {...props} />;
  }
);

PXIconUpload.displayName = "PXIconUpload";

export default PXIconUpload;
