/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/edit-table.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconEditTableDefinition: PXIconDefinition = {
  "name": "PXIconEditTable",
  "slug": "px-edit-table",
  "title": "Edit Table",
  "description": "Modifies rows, columns, cells, or values in tabular or grid-based content.",
  "category": "actions-controls",
  "family": "edit",
  "aliases": [
    "table-edit",
    "grid-edit",
    "edit-cell",
    "edit-cells",
    "modify-table"
  ],
  "tags": [
    "table",
    "grid",
    "row",
    "column",
    "cell",
    "cells",
    "data"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 4h15v1h1v1h1v5h-2V6H5v12h5v2H3V4zm2 5h11v2H5V9zm5-3v5h2V6h-2zm0 7v5h2v-5h-2z M19 11h2v1h-2z M18 12h1v1h-1z M20 12h1v1h-1z M16 13h4v2h-4z M14 15h4v2h-4z M13 17h1v1h-1z M15 17h1v1h-1z M12 18h2v1h-2z M11 19h2v2h-2z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconEditTable - Edit Table
 * Modifies rows, columns, cells, or values in tabular or grid-based content.
 * Canonical: PXIconEditTable
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconEditTable = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconEditTableDefinition} {...props} />;
  }
);

PXIconEditTable.displayName = "PXIconEditTable";

export default PXIconEditTable;
