/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/insert-below.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconInsertBelowDefinition: PXIconDefinition = {
  "name": "PXIconInsertBelow",
  "slug": "px-insert-below",
  "title": "Insert Below",
  "description": "Inserts a new element below an existing element.",
  "category": "actions-controls",
  "family": "insert",
  "aliases": [
    "insert-bottom",
    "insert-down",
    "add-below"
  ],
  "tags": [
    "insert",
    "layout",
    "below",
    "bottom",
    "down"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 4h14v1h1v6h-1v1H5v-1H4V5h1V4z M11 13h2v3h3v2h-3v3h-2v-3H8v-2h3v-3z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconInsertBelow - Insert Below
 * Inserts a new element below an existing element.
 * Canonical: PXIconInsertBelow
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconInsertBelow = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconInsertBelowDefinition as any} {...props} />;
  }
);

PXIconInsertBelow.displayName = "PXIconInsertBelow";

export default PXIconInsertBelow;
