/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/remove-square.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconRemoveSquareDefinition: PXIconDefinition = {
  "name": "PXIconRemoveSquare",
  "slug": "px-remove-square",
  "title": "Remove Square",
  "description": "Removes or subtracts an item using a compact square-contained action symbol.",
  "category": "actions-controls",
  "family": "remove",
  "aliases": [
    "minus-square",
    "subtract-square"
  ],
  "tags": [
    "remove",
    "control",
    "decrease",
    "square"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v2h2v14h-2v2H5v-2H3V5h2V3z M7 11h10v2H7v-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconRemoveSquare - Remove Square
 * Removes or subtracts an item using a compact square-contained action symbol.
 * Canonical: PXIconRemoveSquare
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconRemoveSquare = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconRemoveSquareDefinition as any} {...props} />;
  }
);

PXIconRemoveSquare.displayName = "PXIconRemoveSquare";

export default PXIconRemoveSquare;
