/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/save-down.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSaveDownDefinition: PXIconDefinition = {
  "name": "PXIconSaveDown",
  "slug": "px-save-down",
  "title": "Save Down",
  "description": "Pixel icon for save; down-oriented variant.",
  "category": "actions-controls",
  "family": "save",
  "aliases": [
    "store-down",
    "persist-down",
    "disk-down",
    "save-download"
  ],
  "tags": [
    "save",
    "down",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M11 16v2H9v2h2v2h2v-2h2v-2h-2v-2h-2z M5 14h12v-1h1v-1h1V2H5v12zm3-2h7v-2H8v2zm1-4h7V4H9v4z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconSaveDown - Save Down
 * Pixel icon for save; down-oriented variant.
 * Canonical: PXIconSaveDown
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSaveDown = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSaveDownDefinition} {...props} />;
  }
);

PXIconSaveDown.displayName = "PXIconSaveDown";

export default PXIconSaveDown;
