/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/refresh.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconRefreshDefinition: PXIconDefinition = {
  "name": "PXIconRefresh",
  "slug": "px-refresh",
  "title": "Refresh",
  "description": "Dual circular pixel arrows for reloading or synchronizing data.",
  "category": "actions",
  "family": "refresh",
  "aliases": [
    "reload",
    "sync"
  ],
  "tags": [
    "reload",
    "sync",
    "cycle",
    "rotate",
    "repeat"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M12 3a9 9 0 0 0-8 5V4H2v7h7V9H5.5A7 7 0 0 1 19 12h2a9 9 0 0 0-9-9zm7 6h-2a7 7 0 0 1-13.5 3H2a9 9 0 0 0 17 4v4h2v-7h-7v2h3.5A7 7 0 0 1 19 9z"
      }
    ]
  },
  "animation": {
    "type": "spin",
    "family": "loop",
    "trigger": "always"
  },
  "status": "stable"
};

/**
 * PXIconRefresh - Refresh
 * Dual circular pixel arrows for reloading or synchronizing data.
 * Canonical: PXIconRefresh
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconRefresh = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconRefreshDefinition} {...props} />;
  }
);

PXIconRefresh.displayName = "PXIconRefresh";

export default PXIconRefresh;
