/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/edit.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconEditDefinition: PXIconDefinition = {
  "name": "PXIconEdit",
  "slug": "px-edit",
  "title": "Edit",
  "description": "Modifies or updates an existing item, value, object, or piece of content.",
  "category": "actions-controls",
  "family": "edit",
  "aliases": [
    "modify",
    "change",
    "update",
    "revise",
    "pencil",
    "write"
  ],
  "tags": [
    "editing",
    "action",
    "content",
    "toolbar",
    "modify"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 21h2v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2V3h-2v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v2H3v2z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconEdit - Edit
 * Modifies or updates an existing item, value, object, or piece of content.
 * Canonical: PXIconEdit
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconEdit = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconEditDefinition} {...props} />;
  }
);

PXIconEdit.displayName = "PXIconEdit";

export default PXIconEdit;
