/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/check-all.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCheckAllDefinition: PXIconDefinition = {
  "name": "PXIconCheckAll",
  "slug": "px-check-all",
  "title": "Check All",
  "description": "Complete or confirm every item in a group, collection, or batch.",
  "category": "actions-controls",
  "family": "check",
  "aliases": [
    "complete-all",
    "confirm-all",
    "mark-all",
    "select-complete"
  ],
  "tags": [
    "check",
    "complete",
    "confirm",
    "batch",
    "all",
    "group"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 6h6v2H3V6zm0 5h4v2H3v-2zm0 5h6v2H3v-2z M8 12h2v1h1v1h1v2h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h3v3h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-3v-1h-1v-1h-1v-1H8v-3z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconCheckAll - Check All
 * Complete or confirm every item in a group, collection, or batch.
 * Canonical: PXIconCheckAll
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconCheckAll = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCheckAllDefinition} {...props} />;
  }
);

PXIconCheckAll.displayName = "PXIconCheckAll";

export default PXIconCheckAll;
