/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/checkbox-indeterminate.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCheckboxIndeterminateDefinition: PXIconDefinition = {
  "name": "PXIconCheckboxIndeterminate",
  "slug": "px-checkbox-indeterminate",
  "title": "Checkbox Indeterminate",
  "description": "Represents a checkbox containing a mixed or partially selected state.",
  "category": "actions-controls",
  "family": "checkbox",
  "aliases": [
    "mixed",
    "partial",
    "checkbox-mixed",
    "indeterminate"
  ],
  "tags": [
    "checkbox",
    "partial",
    "selection",
    "mixed",
    "form",
    "control"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v1h1v1h1v14h-1v1h-1v1H5v-1H4v-1H3V5h1V4h1V3zm0 2v14h14V5H5z M7 11h10v2H7v-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconCheckboxIndeterminate - Checkbox Indeterminate
 * Represents a checkbox containing a mixed or partially selected state.
 * Canonical: PXIconCheckboxIndeterminate
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconCheckboxIndeterminate = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCheckboxIndeterminateDefinition} {...props} />;
  }
);

PXIconCheckboxIndeterminate.displayName = "PXIconCheckboxIndeterminate";

export default PXIconCheckboxIndeterminate;
