/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/edit-document.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconEditDocumentDefinition: PXIconDefinition = {
  "name": "PXIconEditDocument",
  "slug": "px-edit-document",
  "title": "Edit Document",
  "description": "Modifies the contents or properties of a document or file.",
  "category": "actions-controls",
  "family": "edit",
  "aliases": [
    "edit-file",
    "document-edit",
    "modify-document",
    "file-pencil"
  ],
  "tags": [
    "document",
    "file",
    "content",
    "editor",
    "modify"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 3h10v1h1v1h1v1h1v5h-2V7h-1V6h-1V5H6v14h4v2H4V3zm10 0v3h3l-3-3z M19 11h2v1h-2z M18 12h1v1h-1z M20 12h1v1h-1z M16 13h4v2h-4z M14 15h4v2h-4z M13 17h1v1h-1z M15 17h1v1h-1z M12 18h2v1h-2z M11 19h2v2h-2z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconEditDocument - Edit Document
 * Modifies the contents or properties of a document or file.
 * Canonical: PXIconEditDocument
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconEditDocument = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconEditDocumentDefinition} {...props} />;
  }
);

PXIconEditDocument.displayName = "PXIconEditDocument";

export default PXIconEditDocument;
