/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/power.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconPowerDefinition: PXIconDefinition = {
  "name": "PXIconPower",
  "slug": "px-power",
  "title": "Power",
  "description": "Circular power switch with top vertical break for system on/off.",
  "category": "actions",
  "family": "power",
  "aliases": [
    "shutdown",
    "switch",
    "toggle"
  ],
  "tags": [
    "shutdown",
    "on",
    "off",
    "standby",
    "reboot"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M11 2h2v9h-2V2zm5.7 3.3l1.4 1.4A8 8 0 1 1 5.9 6.7l1.4-1.4A6 6 0 1 0 16.7 5.3z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconPower - Power
 * Circular power switch with top vertical break for system on/off.
 * Canonical: PXIconPower
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconPower = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconPowerDefinition as any} {...props} />;
  }
);

PXIconPower.displayName = "PXIconPower";

export default PXIconPower;
