/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/copy-large.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCopyLargeDefinition: PXIconDefinition = {
  "name": "PXIconCopyLarge",
  "slug": "px-copy-large",
  "title": "Copy Large",
  "description": "Pixel icon for copy; large-emphasis variant.",
  "category": "actions-controls",
  "family": "copy",
  "aliases": [
    "duplicate-large",
    "clone-large",
    "copy-expanded"
  ],
  "tags": [
    "copy",
    "large",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M7 2h15v15h-5v-2h3V4H9v3H7V2z M2 7h15v15H2V7zm2 2v11h11V9H4z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconCopyLarge - Copy Large
 * Pixel icon for copy; large-emphasis variant.
 * Canonical: PXIconCopyLarge
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconCopyLarge = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCopyLargeDefinition} {...props} />;
  }
);

PXIconCopyLarge.displayName = "PXIconCopyLarge";

export default PXIconCopyLarge;
