/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/bot.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconBotDefinition: PXIconDefinition = {
  "name": "PXIconBot",
  "slug": "px-bot",
  "title": "Bot",
  "description": "Stepped robot head with top sensor antenna and dual digital eyes.",
  "category": "actions",
  "family": "bot",
  "aliases": [
    "robot",
    "agent",
    "assistant"
  ],
  "tags": [
    "robot",
    "assistant",
    "ai",
    "machine",
    "agent"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M11 2h2v3h-2V2zM4 7h16v13H4V7zm2 2v9h12V9H6zm2 3h3v3H8v-3zm5 0h3v3h-3v-3zM2 11h2v4H2v-4zm18 0h2v4h-2v-4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconBot - Bot
 * Stepped robot head with top sensor antenna and dual digital eyes.
 * Canonical: PXIconBot
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconBot = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconBotDefinition as any} {...props} />;
  }
);

PXIconBot.displayName = "PXIconBot";

export default PXIconBot;
