/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/communication/bell.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconBellDefinition: PXIconDefinition = {
  "name": "PXIconBell",
  "slug": "px-bell",
  "title": "Bell",
  "description": "Notification alert bell with clapper, supports stepped wiggle animation.",
  "category": "communication",
  "family": "bell",
  "aliases": [
    "notification",
    "alert",
    "alarm"
  ],
  "tags": [
    "alert",
    "notification",
    "alarm",
    "reminder",
    "ring"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M11 2h2v2h2a5 5 0 0 1 5 5v5l2 2v2H2v-2l2-2V9a5 5 0 0 1 5-5h2V2zm-5 14h12v-7a3 3 0 0 0-3-3H9a3 3 0 0 0-3 3v7zm4 3h4v1a2 2 0 0 1-4 0v-1z"
      }
    ],
    "filled": [
      {
        "d": "M11 2h2v2h2a5 5 0 0 1 5 5v5l2 2v2H2v-2l2-2V9a5 5 0 0 1 5-5h2V2zm-1 17h4v1a2 2 0 0 1-4 0v-1z"
      }
    ]
  },
  "animation": {
    "type": "wiggle",
    "family": "attention",
    "trigger": "hover"
  },
  "status": "stable"
};

/**
 * PXIconBell - Bell
 * Notification alert bell with clapper, supports stepped wiggle animation.
 * Canonical: PXIconBell
 * Package: @pxui/react
 * Category: communication
 * Grid: 24x24
 */
export const PXIconBell = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconBellDefinition as any} {...props} />;
  }
);

PXIconBell.displayName = "PXIconBell";

export default PXIconBell;
