/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/commerce/tag.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconTagDefinition: PXIconDefinition = {
  "name": "PXIconTag",
  "slug": "px-tag",
  "title": "Tag",
  "description": "Merchandise sales price tag with ribbon thread eyelet.",
  "category": "commerce",
  "family": "tag",
  "aliases": [
    "label",
    "badge",
    "sale"
  ],
  "tags": [
    "label",
    "price",
    "discount",
    "sale",
    "metadata"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M12.5 2H2v10.5l9.5 9.5 10.5-10.5L12.5 2zM4 4h7.7L19.3 12 12 19.3 4 11.7V4zm3 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"
      }
    ],
    "filled": [
      {
        "d": "M12.5 2H2v10.5l9.5 9.5 10.5-10.5L12.5 2zM7 6a2 2 0 1 1 0 4 2 2 0 0 1 0-4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconTag - Tag
 * Merchandise sales price tag with ribbon thread eyelet.
 * Canonical: PXIconTag
 * Package: @pxui/react
 * Category: commerce
 * Grid: 24x24
 */
export const PXIconTag = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconTagDefinition as any} {...props} />;
  }
);

PXIconTag.displayName = "PXIconTag";

export default PXIconTag;
