/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/insert-left.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconInsertLeftDefinition: PXIconDefinition = {
  "name": "PXIconInsertLeft",
  "slug": "px-insert-left",
  "title": "Insert Left",
  "description": "Inserts an element immediately before or to the left of an existing element.",
  "category": "actions-controls",
  "family": "insert",
  "aliases": [
    "prepend",
    "insert-before",
    "add-left"
  ],
  "tags": [
    "insert",
    "layout",
    "left",
    "before",
    "prepend"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M6 8h2v3h3v2H8v3H6v-3H3v-2h3V8z M14 4h6v1h1v14h-1v1h-6v-1h-1V5h1V4z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconInsertLeft - Insert Left
 * Inserts an element immediately before or to the left of an existing element.
 * Canonical: PXIconInsertLeft
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconInsertLeft = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconInsertLeftDefinition} {...props} />;
  }
);

PXIconInsertLeft.displayName = "PXIconInsertLeft";

export default PXIconInsertLeft;
