/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/pin.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconPinDefinition: PXIconDefinition = {
  "name": "PXIconPin",
  "slug": "px-pin",
  "title": "Pin",
  "description": "Stepped thumbtack pushpin for pinning items to boards.",
  "category": "actions",
  "family": "pin",
  "aliases": [
    "thumbtack",
    "attach"
  ],
  "tags": [
    "thumbtack",
    "board",
    "attach",
    "stick",
    "fasten"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M16 2l6 6-3 3-1-1-4 4v5l-2 2-1-6-4-4-1 1-3-3 6-6 4 4z"
      }
    ],
    "filled": [
      {
        "d": "M16 2l6 6-3 3-1-1-4 4v5l-2 2-1-6-4-4-1 1-3-3 6-6 4 4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconPin - Pin
 * Stepped thumbtack pushpin for pinning items to boards.
 * Canonical: PXIconPin
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconPin = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconPinDefinition} {...props} />;
  }
);

PXIconPin.displayName = "PXIconPin";

export default PXIconPin;
