/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/zoom-in.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconZoomInDefinition: PXIconDefinition = {
  "name": "PXIconZoomIn",
  "slug": "px-zoom-in",
  "title": "Zoom In",
  "description": "Magnifier lens containing a stepped plus sign for scaling upward.",
  "category": "actions",
  "family": "zoom",
  "aliases": [
    "magnify-plus",
    "enlarge"
  ],
  "tags": [
    "magnify",
    "enlarge",
    "scale-up",
    "plus"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M9 3h6v2h2v2h2v6h-2v2h-2v2H9v-2H7v-2H5V9h2V7h2V5zm6 4H9v6h6V7zm1 8h2v2h-2zm2 2h2v2h-2zm2 2h2v2h-2zm-9-8h2v2h2v2h-2v2h-2v-2H9v-2h2V9z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconZoomIn - Zoom In
 * Magnifier lens containing a stepped plus sign for scaling upward.
 * Canonical: PXIconZoomIn
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconZoomIn = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconZoomInDefinition} {...props} />;
  }
);

PXIconZoomIn.displayName = "PXIconZoomIn";

export default PXIconZoomIn;
