/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/check-square.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCheckSquareDefinition: PXIconDefinition = {
  "name": "PXIconCheckSquare",
  "slug": "px-check-square",
  "title": "Check Square",
  "description": "Indicates confirmation or successful completion within a square-contained state.",
  "category": "actions-controls",
  "family": "check",
  "aliases": [
    "success-square",
    "complete-square",
    "tick-square",
    "confirmed-square"
  ],
  "tags": [
    "confirmation",
    "success",
    "square",
    "status",
    "complete"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v2h2v14h-2v2H5v-2H3V5h2V3z M7 11h2v1h1v1h1v1h1v-1h1v-1h1v-1h1v-1h2v2h-1v1h-1v1h-1v1h-1v1h-1v1h-2v-1h-1v-1h-1v-1H7v-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconCheckSquare - Check Square
 * Indicates confirmation or successful completion within a square-contained state.
 * Canonical: PXIconCheckSquare
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconCheckSquare = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCheckSquareDefinition as any} {...props} />;
  }
);

PXIconCheckSquare.displayName = "PXIconCheckSquare";

export default PXIconCheckSquare;
