/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/selection-check.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSelectionCheckDefinition: PXIconDefinition = {
  "name": "PXIconSelectionCheck",
  "slug": "px-selection-check",
  "title": "Selection Check",
  "description": "Confirms a selected object, region, range, or collection.",
  "category": "actions-controls",
  "family": "check",
  "aliases": [
    "selected",
    "confirm-selection",
    "selection-complete"
  ],
  "tags": [
    "selection",
    "check",
    "confirm",
    "bounding-box",
    "editor",
    "control"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 3h5v2H5v3H3V3zm13 0h5v5h-2V5h-3V3zM3 16h2v3h3v2H3v-5zm16 0h2v5h-5v-2h3v-3z M7 11h2v1h1v1h1v1h1v-1h1v-1h1v-1h1v-1h2v2h-1v1h-1v1h-1v1h-1v1h-1v1h-2v-1h-1v-1h-1v-1H7v-2z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconSelectionCheck - Selection Check
 * Confirms a selected object, region, range, or collection.
 * Canonical: PXIconSelectionCheck
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSelectionCheck = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSelectionCheckDefinition as any} {...props} />;
  }
);

PXIconSelectionCheck.displayName = "PXIconSelectionCheck";

export default PXIconSelectionCheck;
