/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/development/code.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCodeDefinition: PXIconDefinition = {
  "name": "PXIconCode",
  "slug": "px-code",
  "title": "Code",
  "description": "Stepped angle brackets representing code syntax, HTML, and programming.",
  "category": "development",
  "family": "code",
  "aliases": [
    "brackets",
    "syntax",
    "developer"
  ],
  "tags": [
    "brackets",
    "syntax",
    "html",
    "developer",
    "markup"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M8 6l-6 6 6 6 1.4-1.4L4.8 12l4.6-4.6L8 6zm8 0l-1.4 1.4L19.2 12l-4.6 4.6L16 18l6-6-6-6z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconCode - Code
 * Stepped angle brackets representing code syntax, HTML, and programming.
 * Canonical: PXIconCode
 * Package: @pxui/react
 * Category: development
 * Grid: 24x24
 */
export const PXIconCode = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCodeDefinition as any} {...props} />;
  }
);

PXIconCode.displayName = "PXIconCode";

export default PXIconCode;
