/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/media/volume-2.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconVolume2Definition: PXIconDefinition = {
  "name": "PXIconVolume2",
  "slug": "px-volume-2",
  "title": "Volume High",
  "description": "Speaker horn with stepped sonic waves for loud sound playback.",
  "category": "media",
  "family": "volume",
  "aliases": [
    "sound",
    "audio",
    "speaker"
  ],
  "tags": [
    "audio",
    "sound",
    "speaker",
    "loud",
    "music"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 9h4l5-5v16l-5-5H3V9zm2 2v2h3l3 3V8l-3 3H5zm11-4a7 7 0 0 1 0 10l-1.4-1.4a5 5 0 0 0 0-7.2L16 7zm3-3a11 11 0 0 1 0 16l-1.4-1.4a9 9 0 0 0 0-13.2L19 4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconVolume2 - Volume High
 * Speaker horn with stepped sonic waves for loud sound playback.
 * Canonical: PXIconVolume2
 * Package: @pxui/react
 * Category: media
 * Grid: 24x24
 */
export const PXIconVolume2 = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconVolume2Definition} {...props} />;
  }
);

PXIconVolume2.displayName = "PXIconVolume2";

export default PXIconVolume2;
