/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/minimize.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconMinimizeDefinition: PXIconDefinition = {
  "name": "PXIconMinimize",
  "slug": "px-minimize",
  "title": "Minimize",
  "description": "Four corner markers pointing inward for exiting fullscreen.",
  "category": "actions",
  "family": "minimize",
  "aliases": [
    "collapse",
    "restore"
  ],
  "tags": [
    "collapse",
    "shrink",
    "window",
    "restore"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M9 3v4H5v2h6V3H9zm6 0v6h6V7h-4V3h-2zm-6 12H3v2h4v4h2v-6zm6 0v6h2v-4h4v-2h-6z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconMinimize - Minimize
 * Four corner markers pointing inward for exiting fullscreen.
 * Canonical: PXIconMinimize
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconMinimize = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconMinimizeDefinition as any} {...props} />;
  }
);

PXIconMinimize.displayName = "PXIconMinimize";

export default PXIconMinimize;
