/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/commerce/shopping-cart.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconShoppingCartDefinition: PXIconDefinition = {
  "name": "PXIconShoppingCart",
  "slug": "px-shopping-cart",
  "title": "Shopping Cart",
  "description": "Wheeled supermarket trolley for e-commerce checkout and baskets.",
  "category": "commerce",
  "family": "shopping",
  "aliases": [
    "cart",
    "store",
    "buy"
  ],
  "tags": [
    "store",
    "basket",
    "buy",
    "ecommerce",
    "purchase"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M2 3h3l2.6 11.2A3 3 0 0 0 10.5 17h8a3 3 0 0 0 2.9-2.2L23 7H6M8 21a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm10 0a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconShoppingCart - Shopping Cart
 * Wheeled supermarket trolley for e-commerce checkout and baskets.
 * Canonical: PXIconShoppingCart
 * Package: @pxui/react
 * Category: commerce
 * Grid: 24x24
 */
export const PXIconShoppingCart = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconShoppingCartDefinition as any} {...props} />;
  }
);

PXIconShoppingCart.displayName = "PXIconShoppingCart";

export default PXIconShoppingCart;
