/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/arrows/chevron-right.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconChevronRightDefinition: PXIconDefinition = {
  "name": "PXIconChevronRight",
  "slug": "px-chevron-right",
  "title": "Chevron Right",
  "description": "Stepped pixel chevron angle bracket pointing right.",
  "category": "arrows",
  "family": "chevron",
  "aliases": [
    "angle-right"
  ],
  "tags": [
    "right",
    "angle",
    "next",
    "breadcrumb"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M9 4l-1.4 1.4L14.2 12l-6.6 6.6L9 20l8-8-8-8z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconChevronRight - Chevron Right
 * Stepped pixel chevron angle bracket pointing right.
 * Canonical: PXIconChevronRight
 * Package: @pxui/react
 * Category: arrows
 * Grid: 24x24
 */
export const PXIconChevronRight = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconChevronRightDefinition} {...props} />;
  }
);

PXIconChevronRight.displayName = "PXIconChevronRight";

export default PXIconChevronRight;
