/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/security/key.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconKeyDefinition: PXIconDefinition = {
  "name": "PXIconKey",
  "slug": "px-key",
  "title": "Key",
  "description": "Classic skeleton key with bow ring and stepped ward teeth.",
  "category": "security",
  "family": "key",
  "aliases": [
    "auth",
    "credential",
    "password"
  ],
  "tags": [
    "auth",
    "token",
    "credential",
    "password",
    "access"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M7 4a5 5 0 0 0-4.9 6.2L2 11v4h4v-2h2v-2h2.2A5 5 0 1 0 7 4zm0 2a3 3 0 1 1-2.8 4.1L5.6 9H6v2H4.4L4 11.4V13h2v-1h2v-1h1.4l.7-.7A3 3 0 0 1 7 6z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconKey - Key
 * Classic skeleton key with bow ring and stepped ward teeth.
 * Canonical: PXIconKey
 * Package: @pxui/react
 * Category: security
 * Grid: 24x24
 */
export const PXIconKey = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconKeyDefinition} {...props} />;
  }
);

PXIconKey.displayName = "PXIconKey";

export default PXIconKey;
