/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/sync-right.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSyncRightDefinition: PXIconDefinition = {
  "name": "PXIconSyncRight",
  "slug": "px-sync-right",
  "title": "Sync Right",
  "description": "Pixel icon for sync; right-oriented variant.",
  "category": "actions-controls",
  "family": "sync",
  "aliases": [
    "sync-forward",
    "exchange-right"
  ],
  "tags": [
    "sync",
    "right",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M16 11h2V9h2v2h2v2h-2v2h-2v-2h-2v-2z M11 9h2v3h-2V9zm-4-2h4v2H7V7zm-1-1h2v2H6V6zm-2 1h3v2H4V7zm2 1h2v2H6V8z M3 12h2v3H3v-3zm4 3h4v2H7v-2zm3 1h2v2h-2v-2zm2-1h2v2h-2v-2zm-2-1h2v2h-2v-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "animation": {
    "type": "spin",
    "family": "loop",
    "trigger": "always"
  },
  "status": "experimental"
};

/**
 * PXIconSyncRight - Sync Right
 * Pixel icon for sync; right-oriented variant.
 * Canonical: PXIconSyncRight
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSyncRight = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSyncRightDefinition} {...props} />;
  }
);

PXIconSyncRight.displayName = "PXIconSyncRight";

export default PXIconSyncRight;
