/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/copy-left.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCopyLeftDefinition: PXIconDefinition = {
  "name": "PXIconCopyLeft",
  "slug": "px-copy-left",
  "title": "Copy Left",
  "description": "Pixel icon for copy; left-oriented variant.",
  "category": "actions-controls",
  "family": "copy",
  "aliases": [
    "duplicate-left",
    "clone-left",
    "copy-before"
  ],
  "tags": [
    "copy",
    "left",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M8 11H6V9H4v2H2v2h2v2h2v-2h2v-2z M14 5h8v10h-4v-2h2V7h-4v2h-2V5z M10 9h8v10h-8V9zm2 2v6h4v-6h-4z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconCopyLeft - Copy Left
 * Pixel icon for copy; left-oriented variant.
 * Canonical: PXIconCopyLeft
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconCopyLeft = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCopyLeftDefinition} {...props} />;
  }
);

PXIconCopyLeft.displayName = "PXIconCopyLeft";

export default PXIconCopyLeft;
