/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/edit-locked.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconEditLockedDefinition: PXIconDefinition = {
  "name": "PXIconEditLocked",
  "slug": "px-edit-locked",
  "title": "Edit Locked",
  "description": "Indicates that editable content exists but modification is currently locked or permission-restricted.",
  "category": "actions-controls",
  "family": "edit",
  "aliases": [
    "read-only",
    "editing-locked",
    "cannot-edit",
    "protected-edit"
  ],
  "tags": [
    "edit",
    "lock",
    "permission",
    "read-only",
    "restricted",
    "protected"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M3 19h2v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h1v-1h2V7h-2v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v1h-1v2H3v2z M15 11h4v3h-1v-2h-2v2h-1v-3zm-1 3h6v6h-6v-6z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconEditLocked - Edit Locked
 * Indicates that editable content exists but modification is currently locked or permission-restricted.
 * Canonical: PXIconEditLocked
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconEditLocked = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconEditLockedDefinition as any} {...props} />;
  }
);

PXIconEditLocked.displayName = "PXIconEditLocked";

export default PXIconEditLocked;
