/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/bookmark.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconBookmarkDefinition: PXIconDefinition = {
  "name": "PXIconBookmark",
  "slug": "px-bookmark",
  "title": "Bookmark",
  "description": "Vertical ribbon marker with triangular notched tail for reading points.",
  "category": "actions",
  "family": "bookmark",
  "aliases": [
    "save-mark",
    "pin"
  ],
  "tags": [
    "save",
    "read-later",
    "marker",
    "favorite",
    "tag"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v18l-7-4-7 4V3zm2 2v13.2l5-2.8 5 2.8V5H7z"
      }
    ],
    "filled": [
      {
        "d": "M5 3h14v18l-7-4-7 4V3z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconBookmark - Bookmark
 * Vertical ribbon marker with triangular notched tail for reading points.
 * Canonical: PXIconBookmark
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconBookmark = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconBookmarkDefinition as any} {...props} />;
  }
);

PXIconBookmark.displayName = "PXIconBookmark";

export default PXIconBookmark;
