/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/external-link.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconExternalLinkDefinition: PXIconDefinition = {
  "name": "PXIconExternalLink",
  "slug": "px-external-link",
  "title": "External Link",
  "description": "Open window with upper right departing stepped arrow.",
  "category": "actions",
  "family": "external",
  "aliases": [
    "new-tab",
    "outbound"
  ],
  "tags": [
    "new-tab",
    "outbound",
    "redirect",
    "href",
    "popout"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M19 19H5V5h7V3H3v18h18v-9h-2v7zM14 3v2h3.6l-9.3 9.3 1.4 1.4L19 6.4V10h2V3h-7z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconExternalLink - External Link
 * Open window with upper right departing stepped arrow.
 * Canonical: PXIconExternalLink
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconExternalLink = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconExternalLinkDefinition} {...props} />;
  }
);

PXIconExternalLink.displayName = "PXIconExternalLink";

export default PXIconExternalLink;
