/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/devices/smartphone.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSmartphoneDefinition: PXIconDefinition = {
  "name": "PXIconSmartphone",
  "slug": "px-smartphone",
  "title": "Smartphone",
  "description": "Handheld mobile phone device with touch screen and home indicator.",
  "category": "devices",
  "family": "smartphone",
  "aliases": [
    "phone",
    "mobile"
  ],
  "tags": [
    "phone",
    "mobile",
    "ios",
    "android",
    "device"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M6 2h12v20H6V2zm2 2v16h8V4H8zm3 13h2v2h-2v-2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconSmartphone - Smartphone
 * Handheld mobile phone device with touch screen and home indicator.
 * Canonical: PXIconSmartphone
 * Package: @pxui/react
 * Category: devices
 * Grid: 24x24
 */
export const PXIconSmartphone = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSmartphoneDefinition} {...props} />;
  }
);

PXIconSmartphone.displayName = "PXIconSmartphone";

export default PXIconSmartphone;
