/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/sparkles.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSparklesDefinition: PXIconDefinition = {
  "name": "PXIconSparkles",
  "slug": "px-sparkles",
  "title": "Sparkles",
  "description": "Pixel-native sparkle cluster representing artificial intelligence and magic.",
  "category": "actions",
  "family": "sparkles",
  "aliases": [
    "magic",
    "generate",
    "ai"
  ],
  "tags": [
    "ai",
    "magic",
    "generate",
    "stars",
    "intelligence"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M10 2h2v4h4v2h-4v4h-2V8H6V6h4V2zm7 9h2v2h2v2h-2v2h-2v-2h-2v-2h2v-2zM4 14h2v2h2v2H6v2H4v-2H2v-2h2v-2z"
      }
    ]
  },
  "animation": {
    "type": "blink",
    "family": "reveal",
    "trigger": "hover"
  },
  "status": "stable"
};

/**
 * PXIconSparkles - Sparkles
 * Pixel-native sparkle cluster representing artificial intelligence and magic.
 * Canonical: PXIconSparkles
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconSparkles = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSparklesDefinition} {...props} />;
  }
);

PXIconSparkles.displayName = "PXIconSparkles";

export default PXIconSparkles;
