/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/edit-document.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconEditDocumentDefinition: PXIconDefinition = {
  "name": "PXIconEditDocument",
  "slug": "px-edit-document",
  "title": "Edit Document",
  "description": "Modifies the contents or properties of a document or file.",
  "category": "actions-controls",
  "family": "edit",
  "aliases": [
    "edit-file",
    "document-edit",
    "modify-document",
    "file-pencil"
  ],
  "tags": [
    "document",
    "file",
    "content",
    "editor",
    "modify"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 3h10v1h1v1h1v1h1v6h-2V7h-1V6h-1V5H6v14h5v2H4V3zm10 0v3h3l-3-3z M13 21h3v-1h1v-1h1v-1h1v-1h2v-2h-1v-1h-2v2h-1v1h-1v1h-1v1h-2v2z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconEditDocument - Edit Document
 * Modifies the contents or properties of a document or file.
 * Canonical: PXIconEditDocument
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconEditDocument = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconEditDocumentDefinition} {...props} />;
  }
);

PXIconEditDocument.displayName = "PXIconEditDocument";

export default PXIconEditDocument;
