/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/weather/sun.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSunDefinition: PXIconDefinition = {
  "name": "PXIconSun",
  "slug": "px-sun",
  "title": "Sun",
  "description": "Central solar disc surrounded by 8 stepped radiating light beams.",
  "category": "weather",
  "family": "sun",
  "aliases": [
    "light",
    "day",
    "bright"
  ],
  "tags": [
    "light",
    "day",
    "warmth",
    "bright",
    "weather"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M11 2h2v3h-2V2zm0 17h2v3h-2v-3zM2 11h3v2H2v-2zm17 0h3v2h-3v-2zm-13.6-5l1.4-1.4 2.1 2.1-1.4 1.4-2.1-2.1zm11.3 11.3l1.4-1.4 2.1 2.1-1.4 1.4-2.1-2.1zM6.8 17.2l-2.1 2.1-1.4-1.4 2.1-2.1 1.4 1.4zm11.3-11.3l2.1-2.1 1.4 1.4-2.1 2.1-1.4-1.4zM12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10zm0 2a3 3 0 1 1 0 6 3 3 0 0 1 0-6z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconSun - Sun
 * Central solar disc surrounded by 8 stepped radiating light beams.
 * Canonical: PXIconSun
 * Package: @pxui/react
 * Category: weather
 * Grid: 24x24
 */
export const PXIconSun = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSunDefinition as any} {...props} />;
  }
);

PXIconSun.displayName = "PXIconSun";

export default PXIconSun;
