/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/x.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconXDefinition: PXIconDefinition = {
  "name": "PXIconX",
  "slug": "px-x",
  "title": "X (Close)",
  "description": "Stepped pixel diagonal cross for dismissal, cancel, or deletion.",
  "category": "actions",
  "family": "x",
  "aliases": [
    "close",
    "cancel",
    "cross"
  ],
  "tags": [
    "close",
    "cancel",
    "remove",
    "dismiss",
    "delete",
    "cross"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 5h2v2h2v2h2v2h2V9h2V7h2V5h2v2h-2v2h-2v2h-2v2h2v2h2v2h2v2h-2v-2h-2v-2h-2v-2h-2v2H9v2H7v2H5v-2h2v-2h2v-2h2v-2H9V9H7V7H5V5z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconX - X (Close)
 * Stepped pixel diagonal cross for dismissal, cancel, or deletion.
 * Canonical: PXIconX
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconX = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconXDefinition as any} {...props} />;
  }
);

PXIconX.displayName = "PXIconX";

export default PXIconX;
