/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/subtract.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSubtractDefinition: PXIconDefinition = {
  "name": "PXIconSubtract",
  "slug": "px-subtract",
  "title": "Subtract",
  "description": "Represents numerical subtraction or decreasing a quantity or value.",
  "category": "actions-controls",
  "family": "subtract",
  "aliases": [
    "minus",
    "decrease",
    "math",
    "decrement"
  ],
  "tags": [
    "subtract",
    "minus",
    "decrease",
    "math",
    "value",
    "quantity",
    "calculation"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M6 10h12v4H6v-4z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconSubtract - Subtract
 * Represents numerical subtraction or decreasing a quantity or value.
 * Canonical: PXIconSubtract
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSubtract = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSubtractDefinition as any} {...props} />;
  }
);

PXIconSubtract.displayName = "PXIconSubtract";

export default PXIconSubtract;
