/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/copy-down.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCopyDownDefinition: PXIconDefinition = {
  "name": "PXIconCopyDown",
  "slug": "px-copy-down",
  "title": "Copy Down",
  "description": "Pixel icon for copy; down-oriented variant.",
  "category": "actions-controls",
  "family": "copy",
  "aliases": [
    "duplicate-down",
    "clone-down",
    "copy-below"
  ],
  "tags": [
    "copy",
    "down",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M11 16v2H9v2h2v2h2v-2h2v-2h-2v-2h-2z M9 14h10V6h-4v2h2v4h-6v-2H9v4z M5 10h10V2H5v8zm2-2V4h6v4H7z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconCopyDown - Copy Down
 * Pixel icon for copy; down-oriented variant.
 * Canonical: PXIconCopyDown
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconCopyDown = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCopyDownDefinition} {...props} />;
  }
);

PXIconCopyDown.displayName = "PXIconCopyDown";

export default PXIconCopyDown;
