/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/files/file-text.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconFileTextDefinition: PXIconDefinition = {
  "name": "PXIconFileText",
  "slug": "px-file-text",
  "title": "File Text",
  "description": "Document file with horizontal lines representing text content.",
  "category": "files",
  "family": "file",
  "aliases": [
    "document-text",
    "article"
  ],
  "tags": [
    "document",
    "article",
    "readme",
    "lines",
    "copy"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h9l5 5v13H5V3zm2 2v14h10V9h-4V5H7zm2 6h6v2H9v-2zm0 4h6v2H9v-2zm4-10v2h2l-2-2z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconFileText - File Text
 * Document file with horizontal lines representing text content.
 * Canonical: PXIconFileText
 * Package: @pxui/react
 * Category: files
 * Grid: 24x24
 */
export const PXIconFileText = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconFileTextDefinition as any} {...props} />;
  }
);

PXIconFileText.displayName = "PXIconFileText";

export default PXIconFileText;
