/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/weather/zap.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconZapDefinition: PXIconDefinition = {
  "name": "PXIconZap",
  "slug": "px-zap",
  "title": "Zap",
  "description": "Sharp stepped lightning bolt symbolizing electric charge, energy, and speed.",
  "category": "weather",
  "family": "zap",
  "aliases": [
    "lightning",
    "energy",
    "flash"
  ],
  "tags": [
    "lightning",
    "electricity",
    "energy",
    "fast",
    "speed"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M13 2L3 14h8l-2 8 10-12h-8l2-8zm-1.8 10H7.4l5.4-6.5-.8 3.5h3.8l-5.4 6.5.8-3.5z"
      }
    ],
    "filled": [
      {
        "d": "M13 2L3 14h8l-2 8 10-12h-8l2-8z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconZap - Zap
 * Sharp stepped lightning bolt symbolizing electric charge, energy, and speed.
 * Canonical: PXIconZap
 * Package: @pxui/react
 * Category: weather
 * Grid: 24x24
 */
export const PXIconZap = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconZapDefinition} {...props} />;
  }
);

PXIconZap.displayName = "PXIconZap";

export default PXIconZap;
