/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/subtract-square.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSubtractSquareDefinition: PXIconDefinition = {
  "name": "PXIconSubtractSquare",
  "slug": "px-subtract-square",
  "title": "Subtract Square",
  "description": "Subtraction or decrement action displayed inside a bounded square control.",
  "category": "actions-controls",
  "family": "subtract",
  "aliases": [
    "minus-square-math",
    "decrement-square"
  ],
  "tags": [
    "subtract",
    "minus",
    "square",
    "decrement",
    "decrease",
    "math",
    "control"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v2h2v14h-2v2H5v-2H3V5h2V3z M6 11h12v2H6v-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconSubtractSquare - Subtract Square
 * Subtraction or decrement action displayed inside a bounded square control.
 * Canonical: PXIconSubtractSquare
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSubtractSquare = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSubtractSquareDefinition as any} {...props} />;
  }
);

PXIconSubtractSquare.displayName = "PXIconSubtractSquare";

export default PXIconSubtractSquare;
