/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/close.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCloseDefinition: PXIconDefinition = {
  "name": "PXIconClose",
  "slug": "px-close",
  "title": "Close",
  "description": "Closes, dismisses, cancels, or clears the current surface or context.",
  "category": "actions-controls",
  "family": "close",
  "aliases": [
    "dismiss",
    "cancel",
    "x",
    "exit",
    "clear"
  ],
  "tags": [
    "action",
    "dismiss",
    "cancel",
    "close",
    "clear",
    "dialog"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 4h3v1h1v1h1v1h1v1h2V7h1V6h1V5h1V4h3v3h-1v1h-1v1h-1v1h-1v2h1v1h1v1h1v1h1v3h-3v-1h-1v-1h-1v-1h-1v-1h-2v1h-1v1h-1v1h-1v1H4v-3h1v-1h1v-1h1v-1h1v-2H7V9H6V8H5V7H4V4z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconClose - Close
 * Closes, dismisses, cancels, or clears the current surface or context.
 * Canonical: PXIconClose
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconClose = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCloseDefinition as any} {...props} />;
  }
);

PXIconClose.displayName = "PXIconClose";

export default PXIconClose;
