/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/close-tab.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCloseTabDefinition: PXIconDefinition = {
  "name": "PXIconCloseTab",
  "slug": "px-close-tab",
  "title": "Close Tab",
  "description": "Closes an active document, browser, editor, or workspace tab.",
  "category": "actions-controls",
  "family": "close",
  "aliases": [
    "close-editor-tab",
    "close-document",
    "dismiss-tab"
  ],
  "tags": [
    "close",
    "tab",
    "document",
    "editor",
    "browser",
    "dismiss",
    "workspace"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M2 19h20v2H2v-2z M7 5h10v1h1v1h1v1h1v10H4V8h1V7h1V6h1V5zm-1 3v8h12V8h-1V7h-1V6H8v1H7v1H6zm1 3h5v2H7v-2zm7-1h1v1h1v-1h1v1h-1v1h1v1h-1v1h-1v-1h-1v1h-1v-1h1v-1h-1v-1h1v-1z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconCloseTab - Close Tab
 * Closes an active document, browser, editor, or workspace tab.
 * Canonical: PXIconCloseTab
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconCloseTab = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCloseTabDefinition as any} {...props} />;
  }
);

PXIconCloseTab.displayName = "PXIconCloseTab";

export default PXIconCloseTab;
