/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions/copy.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCopyDefinition: PXIconDefinition = {
  "name": "PXIconCopy",
  "slug": "px-copy",
  "title": "Copy",
  "description": "Dual layered documents representing clipboard copy and duplication.",
  "category": "actions",
  "family": "copy",
  "aliases": [
    "duplicate",
    "clone",
    "clipboard"
  ],
  "tags": [
    "duplicate",
    "clipboard",
    "clone",
    "paste"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 4h10v2H6v12H4V4zm4 4h12v14H8V8zm2 2v10h8V10h-8z"
      }
    ],
    "filled": [
      {
        "d": "M4 4h10v2H6v12H4V4zm4 4h12v14H8V8z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconCopy - Copy
 * Dual layered documents representing clipboard copy and duplication.
 * Canonical: PXIconCopy
 * Package: @pxui/react
 * Category: actions
 * Grid: 24x24
 */
export const PXIconCopy = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCopyDefinition} {...props} />;
  }
);

PXIconCopy.displayName = "PXIconCopy";

export default PXIconCopy;
