/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/weather/cloud.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconCloudDefinition: PXIconDefinition = {
  "name": "PXIconCloud",
  "slug": "px-cloud",
  "title": "Cloud",
  "description": "Pixel cloud contour representing remote storage and meteorology.",
  "category": "weather",
  "family": "cloud",
  "aliases": [
    "cloud-storage",
    "weather"
  ],
  "tags": [
    "weather",
    "cloud-storage",
    "sync",
    "sky",
    "overcast"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M6 18H5a4 4 0 0 1-1.2-7.8A6 6 0 0 1 15 7.4 5 5 0 0 1 20 12a4 4 0 0 1-2 7.5H6zm0-2h12a2 2 0 0 0 0-4h-.7l-.3-.7A4 4 0 0 0 10 8a4 4 0 0 0-4 4.5l-.2.7-.7.2A2 2 0 0 0 6 16z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconCloud - Cloud
 * Pixel cloud contour representing remote storage and meteorology.
 * Canonical: PXIconCloud
 * Package: @pxui/react
 * Category: weather
 * Grid: 24x24
 */
export const PXIconCloud = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconCloudDefinition as any} {...props} />;
  }
);

PXIconCloud.displayName = "PXIconCloud";

export default PXIconCloud;
