/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/save-right.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSaveRightDefinition: PXIconDefinition = {
  "name": "PXIconSaveRight",
  "slug": "px-save-right",
  "title": "Save Right",
  "description": "Pixel icon for save; right-oriented variant.",
  "category": "actions-controls",
  "family": "save",
  "aliases": [
    "store-right",
    "persist-right",
    "disk-right"
  ],
  "tags": [
    "save",
    "right",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M16 11h2V9h2v2h2v2h-2v2h-2v-2h-2v-2z M14 5H4v1H3v1H2v12h12V5zm-3 2H6v2h5V7zm-1 5H5v5h5v-5z",
        "fillRule": "evenodd"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconSaveRight - Save Right
 * Pixel icon for save; right-oriented variant.
 * Canonical: PXIconSaveRight
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSaveRight = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSaveRightDefinition} {...props} />;
  }
);

PXIconSaveRight.displayName = "PXIconSaveRight";

export default PXIconSaveRight;
