/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/media/pause.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconPauseDefinition: PXIconDefinition = {
  "name": "PXIconPause",
  "slug": "px-pause",
  "title": "Pause",
  "description": "Dual vertical pixel columns for halting media playback.",
  "category": "media",
  "family": "pause",
  "aliases": [
    "halt",
    "freeze"
  ],
  "tags": [
    "halt",
    "stop",
    "hold",
    "freeze",
    "break"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 4h4v16H5V4zm10 0h4v16h-4V4z"
      }
    ]
  },
  "status": "stable"
};

/**
 * PXIconPause - Pause
 * Dual vertical pixel columns for halting media playback.
 * Canonical: PXIconPause
 * Package: @pxui/react
 * Category: media
 * Grid: 24x24
 */
export const PXIconPause = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconPauseDefinition} {...props} />;
  }
);

PXIconPause.displayName = "PXIconPause";

export default PXIconPause;
