/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/edit-locked.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconEditLockedDefinition: PXIconDefinition = {
  "name": "PXIconEditLocked",
  "slug": "px-edit-locked",
  "title": "Edit Locked",
  "description": "Indicates that editable content exists but modification is currently locked or permission-restricted.",
  "category": "actions-controls",
  "family": "edit",
  "aliases": [
    "read-only",
    "editing-locked",
    "cannot-edit",
    "protected-edit"
  ],
  "tags": [
    "edit",
    "lock",
    "permission",
    "read-only",
    "restricted",
    "protected"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M11 4h2v1h-2z M10 5h1v1h-1z M12 5h1v1h-1z M8 6h4v2H8z M6 8h4v2H6z M5 10h1v1H5z M7 10h1v1H7z M4 11h2v1H4z M3 12h2v2H3z M15 9h4v2h1v3h-2v-2h-2v2h-2v-3h1V9z M13 14h8v7h-8v-7zm3 2h2v3h-2v-3z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconEditLocked - Edit Locked
 * Indicates that editable content exists but modification is currently locked or permission-restricted.
 * Canonical: PXIconEditLocked
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconEditLocked = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconEditLockedDefinition} {...props} />;
  }
);

PXIconEditLocked.displayName = "PXIconEditLocked";

export default PXIconEditLocked;
