/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/remove.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconRemoveDefinition: PXIconDefinition = {
  "name": "PXIconRemove",
  "slug": "px-remove",
  "title": "Remove",
  "description": "Removes, subtracts, or decreases an item or value.",
  "category": "actions-controls",
  "family": "remove",
  "aliases": [
    "minus",
    "subtract",
    "decrease",
    "delete"
  ],
  "tags": [
    "action",
    "subtraction",
    "control",
    "remove",
    "delete"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M4 10h16v4H4v-4z"
      }
    ]
  },
  "status": "experimental"
};

/**
 * PXIconRemove - Remove
 * Removes, subtracts, or decreases an item or value.
 * Canonical: PXIconRemove
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconRemove = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconRemoveDefinition} {...props} />;
  }
);

PXIconRemove.displayName = "PXIconRemove";

export default PXIconRemove;
