/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/sync-square.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconSyncSquareDefinition: PXIconDefinition = {
  "name": "PXIconSyncSquare",
  "slug": "px-sync-square",
  "title": "Sync Square",
  "description": "Pixel icon for sync; square container.",
  "category": "actions-controls",
  "family": "sync",
  "aliases": [
    "sync-box",
    "synchronize-square"
  ],
  "tags": [
    "sync",
    "square",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M5 3h14v2h2v14h-2v2H5v-2H3V5h2V3z M7 9h2v3H7V9zm2-2h4v2H9V7zm3-1h2v2h-2V6zm1 1h3v2h-3V7zm-1 1h2v2h-2V8z M15 12h2v3h-2v-3zm-6 3h4v2H9v-2zm-1 1h2v2H8v-2zm-3-1h3v2H5v-2zm3-1h2v2H8v-2z",
        "fillRule": "evenodd"
      }
    ]
  },
  "animation": {
    "type": "spin",
    "family": "loop",
    "trigger": "always"
  },
  "status": "experimental"
};

/**
 * PXIconSyncSquare - Sync Square
 * Pixel icon for sync; square container.
 * Canonical: PXIconSyncSquare
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconSyncSquare = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconSyncSquareDefinition} {...props} />;
  }
);

PXIconSyncSquare.displayName = "PXIconSyncSquare";

export default PXIconSyncSquare;
