/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: icons/source/actions-controls/refresh.ts
 */

"use client";

import * as React from "react";
import { PXIconBase } from "@/components/icons/px-icon-base";
import type { PXIconProps, PXIconDefinition } from "@pxui/core";

export const PXIconRefreshDefinition: PXIconDefinition = {
  "name": "PXIconRefresh",
  "slug": "px-refresh",
  "title": "Refresh",
  "description": "Pixel icon for refresh; base form.",
  "category": "actions-controls",
  "family": "refresh",
  "aliases": [
    "reload",
    "renew",
    "retry",
    "cycle",
    "rotate"
  ],
  "tags": [
    "refresh",
    "action",
    "control",
    "ui"
  ],
  "geometry": {
    "grid": 24,
    "paths": [
      {
        "d": "M8 4h7v2H8V4zm6-2h2v2h-2V2zm1 2h4v2h-4V4zm-1 2h2v2h-2V6z M6 6h2v2H6V6z M4 8h2v8H4V8zm2 8h2v2H6v-2zm2 2h8v2H8v-2zm8-2h2v2h-2v-2zm2-6h2v6h-2v-6z",
        "fillRule": "evenodd"
      }
    ]
  },
  "animation": {
    "type": "spin",
    "family": "loop",
    "trigger": "always"
  },
  "status": "experimental"
};

/**
 * PXIconRefresh - Refresh
 * Pixel icon for refresh; base form.
 * Canonical: PXIconRefresh
 * Package: @pxui/react
 * Category: actions-controls
 * Grid: 24x24
 */
export const PXIconRefresh = React.forwardRef<SVGSVGElement, PXIconProps>(
  (props, ref) => {
    return <PXIconBase ref={ref} definition={PXIconRefreshDefinition} {...props} />;
  }
);

PXIconRefresh.displayName = "PXIconRefresh";

export default PXIconRefresh;
