import { describe, it } from "node:test";
import assert from "node:assert/strict";
import crypto from "crypto";
import { CANONICAL_ICONS } from "../../icons/source";
import { normalizeIcon } from "../../tooling/compiler/src/normalize";
import { generateReactComponent } from "../../tooling/generators/react";

describe("PXUI Deterministic Build Contract Gate (Section 9.38)", () => {
  it("should generate byte-identical output across consecutive compilation passes", () => {
    const icon = CANONICAL_ICONS[0];
    const norm1 = normalizeIcon(icon);
    const norm2 = normalizeIcon(icon);

    assert.strictEqual(norm1.geometryHash, norm2.geometryHash, "Geometry hash must be stable");

    const code1 = generateReactComponent(norm1);
    const code2 = generateReactComponent(norm2);

    const hash1 = crypto.createHash("sha256").update(code1).digest("hex");
    const hash2 = crypto.createHash("sha256").update(code2).digest("hex");

    assert.strictEqual(hash1, hash2, "Generated TSX component must be byte-identical");
  });

  it("should not embed non-deterministic timestamps in generated file headers", () => {
    const icon = CANONICAL_ICONS[0];
    const norm = normalizeIcon(icon);
    const code = generateReactComponent(norm);

    assert.ok(!code.includes(new Date().getFullYear().toString() + "-"), "File header must not embed dynamic ISO date strings");
    assert.ok(code.includes("AUTO-GENERATED BY PXUI"), "File header must include canonical generator declaration");
  });
});
