import { describe, it } from "node:test";
import assert from "node:assert/strict";
import fs from "fs";
import path from "path";
import { PXIconHome, PXIconSearch, PXIconBell, PXIconHomeDefinition } from "../../packages/react/src";

describe("PXUI React Package Contract (@pxui/react)", () => {
  it("should export tree-shakeable PXIcon* components with definitions", () => {
    assert.ok(typeof PXIconHome === "object" || typeof PXIconHome === "function");
    assert.ok(typeof PXIconSearch === "object" || typeof PXIconSearch === "function");
    assert.ok(typeof PXIconBell === "object" || typeof PXIconBell === "function");

    assert.strictEqual(PXIconHomeDefinition.name, "PXIconHome");
    assert.strictEqual(PXIconHomeDefinition.slug, "px-home");
    assert.strictEqual(PXIconHomeDefinition.geometry.grid, 24);
  });

  it("should have auto-generated file header in all generated components", () => {
    const generatedDir = path.resolve(__dirname, "../../packages/react/src/generated");
    const homeFile = path.join(generatedDir, "PXIconHome.tsx");
    assert.ok(fs.existsSync(homeFile), "PXIconHome.tsx must exist in generated/");

    const content = fs.readFileSync(homeFile, "utf-8");
    assert.ok(content.includes("AUTO-GENERATED BY PXUI"));
    assert.ok(content.includes("Source: icons/source/navigation/home.ts"));
    assert.ok(content.includes("export const PXIconHome = React.forwardRef"));
  });

  it("should maintain displayName matching canonical name", () => {
    assert.strictEqual(PXIconHome.displayName, "PXIconHome");
    assert.strictEqual(PXIconSearch.displayName, "PXIconSearch");
    assert.strictEqual(PXIconBell.displayName, "PXIconBell");
  });
});
