import { NormalizedIcon } from "../../compiler/src/normalize";

export function generateReactNativeComponent(icon: NormalizedIcon): string {
  const componentName = icon.pascalName;

  const paths = icon.paths
    .map(
      (p) =>
        `      <Path d="${p.d}" fill={color}${p.fillRule ? ` fillRule="${p.fillRule}"` : ""}${p.clipRule ? ` clipRule="${p.clipRule}"` : ""} />`
    )
    .join("\n");
  const filledPaths = icon.filledPaths
    ? icon.filledPaths
        .map(
          (p) =>
            `      <Path d="${p.d}" fill={color}${p.fillRule ? ` fillRule="${p.fillRule}"` : ""}${p.clipRule ? ` clipRule="${p.clipRule}"` : ""} />`
        )
        .join("\n")
    : paths;

  return `/**
 * AUTO-GENERATED BY PXUI.
 *
 * Do not edit this file manually.
 * Source: ${icon.sourceFile}
 */

import React from 'react';
import Svg, { Path } from 'react-native-svg';

export interface ${componentName}Props {
  size?: number | string;
  color?: string;
  filled?: boolean;
}

/**
 * ${componentName} - React Native
 * Canonical Grid: 24x24
 * Package: @pxui/react-native
 */
export const ${componentName}: React.FC<${componentName}Props> = ({
  size = 24,
  color = '#000000',
  filled = false,
}) => {
  const dimension = typeof size === 'string' ? parseInt(size, 10) || 24 : size;
${icon.filledPaths && icon.filledPaths.length > 0 ? "" : "  void filled;\n"}
  return (
    <Svg width={dimension} height={dimension} viewBox="0 0 24 24">
${icon.filledPaths && icon.filledPaths.length > 0 ? `      {filled ? (\n  ${filledPaths}\n      ) : (\n  ${paths}\n      )}` : paths}
    </Svg>
  );
};

export default ${componentName};
`;
}
