import { NormalizedIcon } from "../../compiler/src/normalize";

export function generateSvgAsset(icon: NormalizedIcon, filled = false): string {
  const paths = filled && icon.filledPaths && icon.filledPaths.length > 0
    ? icon.filledPaths
    : icon.paths;

  const pathElements = paths
    .map(
      (p) =>
        `  <path d="${p.d}" fill="currentColor"${p.fillRule ? ` fill-rule="${p.fillRule}"` : ""}${p.clipRule ? ` clip-rule="${p.clipRule}"` : ""} />`
    )
    .join("\n");

  return `<!-- AUTO-GENERATED BY PXUI from ${icon.sourceFile} -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="currentColor" shape-rendering="crispEdges">
${pathElements}
</svg>
`;
}
