import fs from "fs";
import path from "path";
import { ICONS_CATALOG } from "../lib/icons/catalog";
import {
  generateReactComponentCode,
  generateRegistryItemJson,
  generateRootRegistryJson,
  toPixelComponentName,
  toPXComponentName,
} from "../lib/compiler";
import { validateIconCatalog } from "./validate-icons";

const ICONS_OUT_DIR = path.resolve(__dirname, "../components/icons");
const REGISTRY_OUT_DIR = path.resolve(__dirname, "../public/r");
const SEARCH_INDEX_OUT = path.resolve(__dirname, "../lib/search/search-index.json");

async function build() {
  console.log("\n🚀 [PXUI Compiler] Starting build pipeline...");

  // 1. Validate
  const validation = validateIconCatalog(ICONS_CATALOG);
  if (!validation.valid) {
    console.error("❌ Cannot build icons: Validation failed.");
    process.exit(1);
  }

  // Ensure output directories exist
  fs.mkdirSync(ICONS_OUT_DIR, { recursive: true });
  fs.mkdirSync(REGISTRY_OUT_DIR, { recursive: true });
  fs.mkdirSync(path.dirname(SEARCH_INDEX_OUT), { recursive: true });

  const exportsStatements: string[] = [
    `// Auto-generated by PXUI icon build pipeline. Do not edit directly.\n`,
    `export * from "./px-icon-base";\n`,
  ];

  const searchIndex = [];

  // 2. Generate each component & registry JSON
  for (const icon of ICONS_CATALOG) {
    const componentName = toPXComponentName(icon.name);
    const aliasName = toPixelComponentName(icon.name);
    const componentFileName = `${icon.name}.tsx`;
    const componentFilePath = path.join(ICONS_OUT_DIR, componentFileName);

    // React Component
    const componentCode = generateReactComponentCode(icon);
    fs.writeFileSync(componentFilePath, componentCode, "utf-8");

    // Add to index.ts: export canonical PX* first, and Pixel* alias
    exportsStatements.push(`export { ${componentName}, ${componentName}Definition, ${aliasName}, ${aliasName}Definition } from "./${icon.name}";`);

    // Registry Item JSON: /public/r/px-[name].json and legacy /public/r/[name].json
    const registryItem = generateRegistryItemJson(icon);
    const pxRegistryFilePath = path.join(REGISTRY_OUT_DIR, `px-${icon.name}.json`);
    const legacyRegistryFilePath = path.join(REGISTRY_OUT_DIR, `${icon.name}.json`);
    fs.writeFileSync(pxRegistryFilePath, JSON.stringify(registryItem, null, 2), "utf-8");
    fs.writeFileSync(legacyRegistryFilePath, JSON.stringify({ ...registryItem, name: icon.name }, null, 2), "utf-8");

    // Search Index Entry
    searchIndex.push({
      name: icon.name,
      componentName,
      title: icon.title,
      description: icon.description || "",
      category: icon.category,
      tags: icon.tags,
      aliases: icon.aliases || [],
      animated: Boolean(icon.animation),
      hasFilled: Boolean(icon.filled && icon.filled.length > 0),
      introducedVersion: icon.introducedVersion,
    });
  }

  // 2.5. Generate px-icon-base registry item
  const baseComponentCode = fs.readFileSync(path.join(ICONS_OUT_DIR, "px-icon-base.tsx"), "utf-8");
  const schemaCode = fs.readFileSync(path.resolve(__dirname, "../lib/icons/schema.ts"), "utf-8");
  const { generateBaseRegistryItemJson } = await import("../lib/compiler");
  const baseRegistryItem = generateBaseRegistryItemJson(baseComponentCode, schemaCode);
  fs.writeFileSync(path.join(REGISTRY_OUT_DIR, "px-icon-base.json"), JSON.stringify(baseRegistryItem, null, 2), "utf-8");

  // 3. Write components/icons/index.ts
  const indexPath = path.join(ICONS_OUT_DIR, "index.ts");
  fs.writeFileSync(indexPath, exportsStatements.join("\n") + "\n", "utf-8");

  // 4. Write public/r/registry.json
  const rootRegistry = generateRootRegistryJson(ICONS_CATALOG);
  // Add px-icon-base to items in root registry
  rootRegistry.items.unshift(baseRegistryItem as any);
  const rootRegistryPath = path.join(REGISTRY_OUT_DIR, "registry.json");
  fs.writeFileSync(rootRegistryPath, JSON.stringify(rootRegistry, null, 2), "utf-8");

  // 5. Write lib/search/search-index.json
  fs.writeFileSync(SEARCH_INDEX_OUT, JSON.stringify(searchIndex, null, 2), "utf-8");

  console.log(`✨ Successfully generated:`);
  console.log(`   - ${ICONS_CATALOG.length} React Components in components/icons/`);
  console.log(`   - Root barrel export in components/icons/index.ts`);
  console.log(`   - ${ICONS_CATALOG.length} shadcn Registry JSON files in public/r/`);
  console.log(`   - Root shadcn registry.json in public/r/registry.json`);
  console.log(`   - Precomputed search index in lib/search/search-index.json\n`);
}

build().catch((err) => {
  console.error("❌ Build error:", err);
  process.exit(1);
});
